### ISSUE TITLE
Issue after upgrading to 0.1.13

### ISSUE THREAD

**Issue by maziarz** [tomchristie/apistar#122]
After upgrading this happend. Python 3.5.1

```
>>> from typing import Type
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Type'
 ```

```bash
$ apistar run
Traceback (most recent call last):
  File "/usr/local/bin/apistar", line 7, in <module>
    from apistar.main import main
  File "/usr/local/lib/python3.5/site-packages/apistar/__init__.py", line 8, in <module>
    from apistar.app import App
  File "/usr/local/lib/python3.5/site-packages/apistar/app.py", line 7, in <module>
    from apistar import commands as cmd
  File "/usr/local/lib/python3.5/site-packages/apistar/commands/__init__.py", line 2, in <module>
    from apistar.commands.new import new
  File "/usr/local/lib/python3.5/site-packages/apistar/commands/new.py", line 8, in <module>
    from apistar import schema
  File "/usr/local/lib/python3.5/site-packages/apistar/schema.py", line 2, in <module>
    from typing import Any, Dict, List, Tuple, Type, Union  # noqa
ImportError: cannot import name 'Type'
```

**Comment by maziarz** [comment]
Yay! Fixed in 0.1.14 :dancing_men:

**Comment by tomchristie** [comment]
We do need to be careful tho - the tests locally and on travis didn't pick this up, don't want to reintroduce it at a later date! 😐

**Comment by maziarz** [comment]
Which Python versions are Travis testing with currently?
